### PR TITLE
Remove duplicate record audit method

### PR DESCRIPTION
**Pull request by willpewitt**
Remove some duplicate code, ```NativeBinaryDownloadHandler.record()``` and ```BinaryDownloadHandler.record()```. record is now also a reserved java keyword, so if the Java version is ever increased to >=14 this would be an issue.

Other changes include reorganizing some access modifiers and some formatting.

### CODE REVIEW

**Review by hgeraldino — DISMISSED** [review]
LGTM

**Review by marc0der — CHANGES_REQUESTED** [review]
LGTM, although I'd prefer if we leave the logger variable as it was.

I've always found calling it `LOG` problematic as it implies that it's a constant, which it really isn't. Loggers are mutable objects that are simply statically scoped. Apart from that it looks great!

**Review by marc0der — APPROVED** [review]
Looks great, thanks!

**Comment by marc0der** [comment]
I'll release this into prod within the next day or so.

**Pull request merged**
